/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package study_fizzbuzz;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        new App().execute();
    }

    public void execute() {
        for (int i = 0; i <= 100; i++) {
            System.out.println(this.convertFizzBuzz(i));
        }
    }

    public String convertFizzBuzz(int i) {

        if (i % 15 == 0) {
            return "FizzBuzz";
        } else if (i % 3 == 0) {
            return "Fizz";
        } else if (i % 5 == 0) {
            return "Buzz";
        }
        return String.valueOf(i);
    }
}
